#!/usr/bin/ruby

require "fileutils"

$dir = ARGV.shift

# obtain lock
lock_fp = File.open("#{$dir}/lock", "w")
lock_fp.flock(File::LOCK_EX)
at_exit { File.unlink("#{$dir}/lock") }

# install new version
if File.directory?("#{$dir}/new")
	FileUtils.remove_entry_secure("#{$dir}/current") if File.directory?("#{$dir}/current")
	FileUtils.mv("#{$dir}/new", "#{$dir}/current")
end

# execute the process
system *ARGV
exit $?.exitstatus
